### ISSUE TITLE
Can you please explain more thoroughly how to use? 

### ISSUE THREAD

**Issue by johnearnshaw** [eabdullin/Word2Vec.Net#1]
I'm trying the ConsoleApp project and args -train questions-words.txt -output output.txt

I get a FileNotFoundException filename "output"

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Word2Vec.Net.Distance.InitVocub() in Word2Vec.Net-master\Word2Vec.Net\Distance.cs:line 115

I remove the .txt from output and re-run and get an OverflowException

Arithmetic operation resulted in an overflow.

   at Word2Vec.Net.Distance.InitVocub() in Word2Vec.Net-master\Word2Vec.Net\Distance.cs:line 124

**Comment by eabdullin** [comment]
Hi john! There is old version of Word2Vec implementation. I'll push the update very soon. i think, in a few days. Generally you must set input and output filenames.
Word2VecBuilder.Create()
                .WithTrainFile("trainingFile.txt")
                .WithOutputFile("outputFile.txt")
                .Build();

**Comment by johnearnshaw** [comment]
awesome :) Is the project still pure C#? I noticed some c and compiled libraries in the dev branch

**Comment by kvasnyj** [comment]
Johnearnshaw,
The exception with following code:
var distance = new Distance("output");

You must specify a path to the output file instead of "output" arg.

**Comment by syedmohsinbukhari** [comment]
Hi, this is an awesome project. Can you please add function that helps us extract the vector of a word directly? or is there already a function in there that I am missing?

Thanks for this Word2Vec implementation in C#

**Comment by eabdullin** [comment]
@syedmohsinbukhari, to be honest i don't understand. Can you explain what do you mean?
